services:
  mysql:
    image: mysql:8.0.32
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Secret_101
    networks:
        - high-score-api-network
    volumes:
      - high-score-api-datavolume:/var/lib/mysql
  high-score-api:
      build: 
        context: ./
        dockerfile: ./HighScoreAPI/Dockerfile.development
      restart: always
      depends_on:
        - mysql
      ports:
        - '127.0.0.1:5205:80'
      environment:
        - MYSQL_HOSTNAME=mysql
        - MYSQL_USER=root
        - MYSQL_PASSWORD=Secret_101
        - MYSQL_DATABASE_NAME=HighScoreAPIDev
      networks:
        - high-score-api-network

volumes:
  high-score-api-datavolume:

networks:
 high-score-api-network:
    